### ISSUE TITLE
interface table has many columns 

### ISSUE THREAD

**Issue by gabi2** [yast/yast-fcoe-client#23]
Interfaces dialog possible needs redesign, lines containing interface data shouldn't be to long. Customer needs have to be checked first before deciding which data to show in additional rich text window (already talked to Ken).

**Comment by ancorgs** [comment]
As much as I agree this module would benefit from an UI redesign, this has not seen activity in six years and I doubt creating a Trello card for it would change that in the mid-term. So closing as WONTFIX.
